<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monitor.Contracts\Monitor.Contracts.csproj" />
    <ProjectReference Include="..\Monitor.Core\Monitor.Core.csproj" />
  </ItemGroup>

</Project>
